In [1]:
import torch

list = [[1,2,3],
       [4,5,6]]

tns = torch.Tensor(list)
print(tns.dtype)
print(tns)

tns = torch.FloatTensor(list)
print(tns.dtype)
print(tns)

tns = torch.DoubleTensor(list)
print(tns.dtype)
print(tns)

tns = torch.LongTensor(list)
print(tns.dtype)
print(tns)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


In [2]:
import numpy as np

arr = np.random.rand(3,4)
print(arr)
print(arr.dtype)

tns = torch.from_numpy(arr)
print(tns)
print(tns.dtype)

[[0.852892   0.91294183 0.84476868 0.29369516]
 [0.54080369 0.25182241 0.95220223 0.51158903]
 [0.87745202 0.96922656 0.13775698 0.07446753]]
float64
tensor([[0.8529, 0.9129, 0.8448, 0.2937],
        [0.5408, 0.2518, 0.9522, 0.5116],
        [0.8775, 0.9692, 0.1378, 0.0745]], dtype=torch.float64)
torch.float64


In [3]:
tns0 = torch.zeros(2,3)
tns1 = torch.ones(3,4)
tnsr = torch.randn(4,5)

print(tns0)
print(tns1)
print(tnsr)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[-0.9524, -1.2280,  1.0920, -0.0949, -0.6408],
        [-1.1957,  0.9544,  1.1892,  0.2050, -0.2032],
        [-1.9111, -0.3820,  0.0245,  0.9038,  1.1817],
        [-0.8945,  0.2587, -1.1478,  1.6365, -0.8459]])


In [4]:
arr = tnsr.data.numpy()
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[[-0.952425   -1.2279775   1.0919787  -0.09491978 -0.64083785]
 [-1.195729    0.95435536  1.1892179   0.2049865  -0.20319651]
 [-1.9111108  -0.3819988   0.02449287  0.9038057   1.1816753 ]
 [-0.8945131   0.258737   -1.1478492   1.6365327  -0.84592026]]


In [5]:
print(tnsr)
print("")
tnsr[0,2]=-10
print(tnsr)
print("")
print(tnsr[0:2])
print("")
print(tnsr[:,2])
print("")
print(tnsr[0,2])

tensor([[-0.9524, -1.2280,  1.0920, -0.0949, -0.6408],
        [-1.1957,  0.9544,  1.1892,  0.2050, -0.2032],
        [-1.9111, -0.3820,  0.0245,  0.9038,  1.1817],
        [-0.8945,  0.2587, -1.1478,  1.6365, -0.8459]])

tensor([[ -0.9524,  -1.2280, -10.0000,  -0.0949,  -0.6408],
        [ -1.1957,   0.9544,   1.1892,   0.2050,  -0.2032],
        [ -1.9111,  -0.3820,   0.0245,   0.9038,   1.1817],
        [ -0.8945,   0.2587,  -1.1478,   1.6365,  -0.8459]])

tensor([[ -0.9524,  -1.2280, -10.0000,  -0.0949,  -0.6408],
        [ -1.1957,   0.9544,   1.1892,   0.2050,  -0.2032]])

tensor([-10.0000,   1.1892,   0.0245,  -1.1478])

tensor(-10.)


In [6]:
tnsr1 = torch.randn(2,3)
tnsr2 = torch.randn(2,3)

print(tnsr1)
print(tnsr2)
print("")
print(tnsr1+tnsr2)
print("")
print(tnsr1-tnsr2)
print("")
print(tnsr1*tnsr2)
print("")
print(tnsr1/tnsr2)
print("")
print(torch.mm(tnsr1,tnsr2.T))

tensor([[ 0.6200,  0.5500, -0.4674],
        [-1.0845,  0.3467,  0.2362]])
tensor([[0.0293, 0.4857, 0.0990],
        [1.6865, 1.3040, 1.0150]])

tensor([[ 0.6493,  1.0358, -0.3683],
        [ 0.6020,  1.6506,  1.2512]])

tensor([[ 0.5906,  0.0643, -0.5664],
        [-2.7710, -0.9573, -0.7788]])

tensor([[ 0.0182,  0.2672, -0.0463],
        [-1.8290,  0.4520,  0.2398]])

tensor([[21.1414,  1.1323, -4.7188],
        [-0.6430,  0.2659,  0.2327]])

tensor([[ 0.2391,  1.2884],
        [ 0.1600, -1.1372]])


In [7]:
tnsr = torch.randn(2,3,4)
print(tnsr)
print("")
print(tnsr.size())
print("")
print(tnsr.view(3,8))
print("")
print(tnsr.view(-1))
print("")
print(tnsr.view(tnsr.size(0),-1))

tensor([[[ 0.2831, -0.1379,  1.5500,  0.0503],
         [ 0.1374,  0.1366, -0.6077,  0.7374],
         [ 0.7714, -0.0611, -2.4610,  0.5666]],

        [[ 1.1762, -1.4199, -0.2974, -0.0880],
         [-0.9094,  0.9667,  0.5243,  0.0771],
         [-1.4301, -0.3533, -2.8634,  0.2956]]])

torch.Size([2, 3, 4])

tensor([[ 0.2831, -0.1379,  1.5500,  0.0503,  0.1374,  0.1366, -0.6077,  0.7374],
        [ 0.7714, -0.0611, -2.4610,  0.5666,  1.1762, -1.4199, -0.2974, -0.0880],
        [-0.9094,  0.9667,  0.5243,  0.0771, -1.4301, -0.3533, -2.8634,  0.2956]])

tensor([ 0.2831, -0.1379,  1.5500,  0.0503,  0.1374,  0.1366, -0.6077,  0.7374,
         0.7714, -0.0611, -2.4610,  0.5666,  1.1762, -1.4199, -0.2974, -0.0880,
        -0.9094,  0.9667,  0.5243,  0.0771, -1.4301, -0.3533, -2.8634,  0.2956])

tensor([[ 0.2831, -0.1379,  1.5500,  0.0503,  0.1374,  0.1366, -0.6077,  0.7374,
          0.7714, -0.0611, -2.4610,  0.5666],
        [ 1.1762, -1.4199, -0.2974, -0.0880, -0.9094,  0.9667,  0.5243,  

In [8]:
tns = torch.randn(10)
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")
print(device)

tns = tns.to(device)
print(tns)

cuda
tensor([ 0.9370, -1.2025,  0.0614,  0.8759, -1.2040,  0.2300,  0.2554, -0.2345,
         0.8286, -0.8358], device='cuda:0')


In [10]:
tns1 = torch.randn(7,7,3)
tns2 = torch.randn(147,1)
tns3 = tns1.view(147,1) + tns2
print(tns3)

tensor([[ 0.1351],
        [ 1.0887],
        [ 0.9508],
        [-1.1243],
        [ 1.2361],
        [ 0.1699],
        [ 0.0499],
        [-0.0065],
        [ 0.4588],
        [ 0.0347],
        [-1.7646],
        [ 0.1757],
        [-0.5870],
        [ 0.0739],
        [-2.8422],
        [ 0.2431],
        [ 1.2904],
        [-0.7155],
        [-0.5963],
        [-0.1474],
        [-1.2673],
        [ 1.6741],
        [-0.6915],
        [-0.8280],
        [-2.5512],
        [ 0.2797],
        [ 0.7286],
        [-1.0654],
        [ 2.0693],
        [-0.5860],
        [-2.5605],
        [ 0.3168],
        [ 0.4679],
        [-1.0092],
        [-0.6363],
        [-1.1661],
        [ 0.9364],
        [ 1.7421],
        [ 1.2231],
        [-1.7065],
        [-1.1417],
        [ 0.5793],
        [-1.7522],
        [-0.9991],
        [-0.3534],
        [ 0.8657],
        [ 0.0414],
        [-1.0053],
        [-0.0588],
        [ 1.6441],
        [-0.2680],
        [ 2.6730],
        [ 0.